name: ExchangeRemoteDataSource
options:
  bundleIdPrefix: com.navia.framework
  deploymentTarget:
    iOS: 15
packages:
  RxSwift:
    url: "https://github.com/ReactiveX/RxSwift"
    majorVersion: 6.2.0
targets:
  ExchangeRemoteDataSource:
    type: framework
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: RxSwift
        implicit: true
      - package: RxSwift 
        product: RxCocoa
        implicit: true
    preBuildScripts:
      - path: ../Scripts/preBuildScript.sh
        name: Swiftlint, Sourcery
  ExchangeRemoteDataSourceTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/UnitTests
    dependencies:
      - target: ExchangeRemoteDataSource
        codeSign: false
      # - package: RxSwift 
      #   product: RxTest
      # - package: RxSwift 
      #   product: RxCocoa
  ExchangeRemoteDataSourceIntegrationTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/IntegrationTests
    dependencies:
      - target: ExchangeRemoteDataSource
        codeSign: false
      # - package: RxSwift
      #   product: RxBlocking
schemes:
  ExchangeRemoteDataSource:
    build:
      targets:
        ExchangeRemoteDataSource: all
    test:
      targets: 
        - ExchangeRemoteDataSourceTests 
  ExchangeRemoteDataSourceTests:
    build:
      targets:
        ExchangeRemoteDataSourceTests: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - ExchangeRemoteDataSource
      targets: 
        - ExchangeRemoteDataSourceTests 
  ExchangeRemoteDataSourceIntegrationTests:
    build:
      targets:
        ExchangeRemoteDataSourceIntegrationTests: all
    test:
      targets: 
        - ExchangeRemoteDataSourceIntegrationTests 