name: ExchangeRemoteDataSource
options:
  bundleIdPrefix: com.navia.framework
  deploymentTarget:
    iOS: 15
targets:
  ExchangeRemoteDataSource:
    type: framework
    platform: iOS
    sources:
      - path: Sources
    preBuildScripts:
      - path: ../Scripts/preBuildScript.sh
        name: Swiftlint, Sourcery
  ExchangeRemoteDataSourceTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/UnitTests
    dependencies:
      - target: ExchangeRemoteDataSource
        codeSign: false
  ExchangeRemoteDataSourceIntegrationTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/IntegrationTests
    dependencies:
      - target: ExchangeRemoteDataSource
        codeSign: false
schemes:
  ExchangeRemoteDataSource:
    build:
      targets:
        ExchangeRemoteDataSource: all
    test:
      targets: 
        - ExchangeRemoteDataSourceTests 
  ExchangeRemoteDataSourceTests:
    build:
      targets:
        ExchangeRemoteDataSourceTests: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - ExchangeRemoteDataSource
      targets: 
        - ExchangeRemoteDataSourceTests 
  ExchangeRemoteDataSourceIntegrationTests:
    build:
      targets:
        ExchangeRemoteDataSourceIntegrationTests: all
    test:
      targets: 
        - ExchangeRemoteDataSourceIntegrationTests 
