name: ExchangeSymbolsRepository
options:
  bundleIdPrefix: com.navia.framework
  deploymentTarget:
    iOS: 15
packages:
  RxSwift:
    url: "https://github.com/ReactiveX/RxSwift"
    majorVersion: 6.2.0
  Reachability:
    url: "https://github.com/ashleymills/Reachability.swift"
    majorVersion: 5.1.0
projectReferences:
  ExchangeRemoteDataSource:
    path: ../ExchangeRemoteDataSource/ExchangeRemoteDataSource.xcodeproj
  ExchangeLocalDataSource:
    path: ../ExchangeLocalDataSource/ExchangeLocalDataSource.xcodeproj
targets:
  ExchangeSymbolsRepository:
    type: framework
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: RxSwift
      - package: Reachability
      - package: RxSwift 
        product: RxCocoa
      - target: ExchangeRemoteDataSource/ExchangeRemoteDataSource
      - target: ExchangeLocalDataSource/ExchangeLocalDataSource
    preBuildScripts:
      - path: ../Scripts/preBuildScript.sh
        name: Swiftlint, Sourcery
  ExchangeSymbolsRepositoryTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: ExchangeRemoteDataSource/ExchangeRemoteDataSource
        codeSign: false
schemes:
  ExchangeSymbolsRepository:
    build:
      targets:
        ExchangeSymbolsRepository: all
    test:
      targets: 
        - ExchangeSymbolsRepository 
  ExchangeSymbolsRepositoryTests:
    build:
      targets:
        ExchangeSymbolsRepositoryTests: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - ExchangeSymbolsRepository
      targets: 
        - ExchangeSymbolsRepositoryTests 
