name: ExchangeSymbolsRepository
options:
  bundleIdPrefix: com.navia.framework
  deploymentTarget:
    iOS: 15
projectReferences:
  ExchangeRemoteDataSource:
    path: ../ExchangeRemoteDataSource/ExchangeRemoteDataSource.xcodeproj
  ExchangeLocalDataSource:
    path: ../ExchangeLocalDataSource/ExchangeLocalDataSource.xcodeproj
targets:
  ExchangeSymbolsRepository:
    type: framework
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - target: ExchangeRemoteDataSource/ExchangeRemoteDataSource
      - target: ExchangeLocalDataSource/ExchangeLocalDataSource
    preBuildScripts:
      - path: ../Scripts/preBuildScript.sh
        name: Swiftlint, Sourcery
  ExchangeSymbolsRepositoryTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: ExchangeRemoteDataSource/ExchangeRemoteDataSource
        codeSign: false
schemes:
  ExchangeSymbolsRepository:
    build:
      targets:
        ExchangeSymbolsRepository: all
    test:
      targets: 
        - ExchangeSymbolsRepository 
  ExchangeSymbolsRepositoryTests:
    build:
      targets:
        ExchangeSymbolsRepositoryTests: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - ExchangeSymbolsRepository
      targets: 
        - ExchangeSymbolsRepositoryTests 
