name: ExchangeAPI
options:
  bundleIdPrefix: com.navia.framework.exchangeapi
  deploymentTarget:
    iOS: 15
packages:
  RxSwift:
    url: "https://github.com/ReactiveX/RxSwift"
    majorVersion: 6.2.0
targets:
  ExchangeAPI:
    type: framework
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: RxSwift
    preBuildScripts:
      - path: ../Scripts/preBuildScript.sh
        name: Swiftlint, Sourcery
  ExchangeAPITests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/UnitTests
    dependencies:
      - target: ExchangeAPI
      - package: RxSwift 
        product: RxTest
      - package: RxSwift 
        product: RxCocoa
  ExchangeAPIIntegrationTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/IntegrationTests
    dependencies:
      - target: ExchangeAPI
      - package: RxSwift
        product: RxBlocking
schemes:
  ExchangeAPI:
    build:
      targets:
        ExchangeAPI: all
    test:
      targets: 
        - ExchangeAPITests 
  ExchangeAPITests:
    build:
      targets:
        ExchangeAPITests: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - ExchangeAPI
      targets: 
        - ExchangeAPITests 
  ExchangeAPIIntegrationTests:
    build:
      targets:
        ExchangeAPIIntegrationTests: all
    test:
      targets: 
        - ExchangeAPIIntegrationTests 