name: ExchangeApp
options:
  bundleIdPrefix: com.navia.framework
  deploymentTarget:
    iOS: 15
packages:
  Cleanse:
    url: "https://github.com/square/Cleanse"
    majorVersion: 4.2.6
projectReferences:
  ExchangeAPI:
    path: ../ExchangeAPI/ExchangeAPI.xcodeproj
  ExchangeServices:
    path: ../ExchangeServices/ExchangeServices.xcodeproj
targets:
  ExchangeApp:
    type: application
    platform: iOS
    sources:
      - path: ExchangeApp
    dependencies:
      - target: ExchangeServices/ExchangeServices
      - target: ExchangeAPI/ExchangeAPI
      - package: Cleanse
    preBuildScripts:
      - path: ../Scripts/preBuildScript.sh
        name: Swiftlint, Sourcery
  ExchangeAppUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ExchangeAppTests
    dependencies:
      - target: ExchangeApp
  ExchangeAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ExchangeAppUITests
    dependencies:
      - target: ExchangeApp
schemes:
  ExchangeApp:
    build:
      targets:
        ExchangeApp: all
    test:
      targets: 
        - ExchangeApp 
  ExchangeAppUnitTests:
    build:
      targets:
        ExchangeAppUnitTests: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - ExchangeApp
      targets: 
        - ExchangeAppUnitTests 
  ExchangeAppUITests:
    build:
      targets:
        ExchangeAppUITests: all
    test:
      targets: 
        - ExchangeAppUITests 
