name: ExchangeApp
options:
  bundleIdPrefix: com.navia.framework
  deploymentTarget:
    iOS: 15
packages:
  Cleanse:
    url: "https://github.com/square/Cleanse"
    majorVersion: 4.2.6
  RxSwiftExt:
    url: "https://github.com/RxSwiftCommunity/RxSwiftExt"
    majorVersion: 6.1.0
  NVActivityIndicatorView:
    url: "https://github.com/ninjaprox/NVActivityIndicatorView"
    majorVersion: 5.1.1
  Charts:
    url: "https://github.com/danielgindi/Charts"
    majorVersion: 4.0.1
projectReferences:
  ExchangeRemoteDataSource:
    path: ../ExchangeRemoteDataSource/ExchangeRemoteDataSource.xcodeproj
  ExchangeSymbolsRepository:
    path: ../ExchangeSymbolsRepository/ExchangeSymbolsRepository.xcodeproj
targets:
  ExchangeApp:
    type: application
    platform: iOS
    sources:
      - path: ExchangeApp
    dependencies:
      - target: ExchangeSymbolsRepository/ExchangeSymbolsRepository
      - target: ExchangeRemoteDataSource/ExchangeRemoteDataSource
      - package: Cleanse
      - package: Charts
      - package: RxSwiftExt
      - package: NVActivityIndicatorView
    # preBuildScripts:
    #   - path: ../Scripts/preBuildScript.sh
    #     name: Swiftlint, Sourcery
  ExchangeAppUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ExchangeAppTests
    dependencies:
      - target: ExchangeApp
  ExchangeAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ExchangeAppUITests
    dependencies:
      - target: ExchangeApp
schemes:
  ExchangeApp:
    build:
      targets:
        ExchangeApp: all
    test:
      targets: 
        - ExchangeApp 
  ExchangeAppUnitTests:
    build:
      targets:
        ExchangeAppUnitTests: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - ExchangeApp
      targets: 
        - ExchangeAppUnitTests 
  ExchangeAppUITests:
    build:
      targets:
        ExchangeAppUITests: all
    test:
      targets: 
        - ExchangeAppUITests 
