name: ExchangeServices
options:
  bundleIdPrefix: com.navia.framework
  deploymentTarget:
    iOS: 15
projectReferences:
  ExchangeAPI:
    path: ../ExchangeAPI/ExchangeAPI.xcodeproj
packages:
  RxSwift:
    url: "https://github.com/ReactiveX/RxSwift"
    majorVersion: 6.2.0
targets:
  ExchangeServices:
    type: framework
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: RxSwift
      - target: ExchangeAPI/ExchangeAPI
    preBuildScripts:
      - path: ../Scripts/preBuildScript.sh
        name: Swiftlint, Sourcery
  ExchangeServicesTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: ExchangeAPI/ExchangeAPI
        codeSign: false
      - package: RxSwift 
        product: RxTest
      - package: RxSwift 
        product: RxCocoa
schemes:
  ExchangeServices:
    build:
      targets:
        ExchangeServices: all
    test:
      targets: 
        - ExchangeServices 
  ExchangeServicesTests:
    build:
      targets:
        ExchangeServicesTests: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - ExchangeServices
      targets: 
        - ExchangeServicesTests 
