name: ExchangeRemoteRepository
options:
  bundleIdPrefix: com.navia.framework
  deploymentTarget:
    iOS: 15
targets:
  ExchangeRemoteRepository:
    type: framework
    platform: iOS
    sources:
      - path: Sources
    preBuildScripts:
      - path: ../Scripts/preBuildScript.sh
        name: Swiftlint, Sourcery
  ExchangeRemoteRepositoryTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/UnitTests
    dependencies:
      - target: ExchangeRemoteRepository
        codeSign: false
  ExchangeRemoteRepositoryIntegrationTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/IntegrationTests
    dependencies:
      - target: ExchangeRemoteRepository
        codeSign: false
schemes:
  ExchangeRemoteRepository:
    build:
      targets:
        ExchangeRemoteRepository: all
    test:
      targets: 
        - ExchangeRemoteRepositoryTests 
  ExchangeRemoteRepositoryTests:
    build:
      targets:
        ExchangeRemoteRepositoryTests: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - ExchangeRemoteRepository
      targets: 
        - ExchangeRemoteRepositoryTests 
  ExchangeRemoteRepositoryIntegrationTests:
    build:
      targets:
        ExchangeRemoteRepositoryIntegrationTests: all
    test:
      targets: 
        - ExchangeRemoteRepositoryIntegrationTests 
